PKG_VER="2501"
PKG_CATEGORY="FEX"
PKG_PRETTY_NAME="FEX-Emu"
PKG_DOWNLOADABLE=1

GIT_URL=https://github.com/FEX-Emu/FEX
GIT_COMMIT=v2501

CMAKE_ARGS="-DFEX_BUILD_WITH_ASAN=OFF \
            -DENABLE_LTO=OFF \
            -DENABLE_ASSERTIONS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID=1 \
            -DBUILD_TESTS=OFF"

# Only build on ARM64
BLACKLIST_ARCH=x86_64
