PKG_VER="1.11"
PKG_CATEGORY="System"
SRC_URL="https://deb.debian.org/debian/pool/main/c/cabextract/cabextract_1.11.orig.tar.gz"
CONFIGURE_ARGS="--host=$TOOLCHAIN_TRIPLE host_alias=$TOOLCHAIN_TRIPLE"
DEPENDENCIES=""
